<!DOCTYPE html>
<html>
<style type="text/css">
  body{
    font-family: sans-serif;
    font-weight: normal;
  }
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div.main-width {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
  width: 750px;
  margin: 60px auto;
}

ul {
    list-style: none;
    text-decoration: none;
    line-height: 35px;
    font-size: 20px;
    color: blue;
}

a{
  color: blue;
  font-size: 20px;
}



@keyframes ldio-tiuij0da2nb {
  0% {
    opacity: 1;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1.5,1.5);
  } 100% {
    opacity: 0;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1,1);
  }
}
.ldio-tiuij0da2nb div > div {
  position: absolute;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: #9c9494;
  animation: ldio-tiuij0da2nb 0.6711409395973155s linear infinite;
}.ldio-tiuij0da2nb div:nth-child(1) > div {
  left: 74px;
  top: 44px;
  animation-delay: -0.6152125279642059s;
}
.ldio-tiuij0da2nb > div:nth-child(1) {
  transform: rotate(0deg);
  transform-origin: 80px 50px;
}.ldio-tiuij0da2nb div:nth-child(2) > div {
  left: 70px;
  top: 59px;
  animation-delay: -0.5592841163310962s;
}
.ldio-tiuij0da2nb > div:nth-child(2) {
  transform: rotate(30deg);
  transform-origin: 76px 65px;
}.ldio-tiuij0da2nb div:nth-child(3) > div {
  left: 59px;
  top: 70px;
  animation-delay: -0.5033557046979866s;
}
.ldio-tiuij0da2nb > div:nth-child(3) {
  transform: rotate(60deg);
  transform-origin: 65px 76px;
}.ldio-tiuij0da2nb div:nth-child(4) > div {
  left: 44px;
  top: 74px;
  animation-delay: -0.447427293064877s;
}
.ldio-tiuij0da2nb > div:nth-child(4) {
  transform: rotate(90deg);
  transform-origin: 50px 80px;
}.ldio-tiuij0da2nb div:nth-child(5) > div {
  left: 29px;
  top: 70px;
  animation-delay: -0.39149888143176736s;
}
.ldio-tiuij0da2nb > div:nth-child(5) {
  transform: rotate(120deg);
  transform-origin: 35px 76px;
}.ldio-tiuij0da2nb div:nth-child(6) > div {
  left: 18px;
  top: 59px;
  animation-delay: -0.33557046979865773s;
}
.ldio-tiuij0da2nb > div:nth-child(6) {
  transform: rotate(150deg);
  transform-origin: 24px 65px;
}.ldio-tiuij0da2nb div:nth-child(7) > div {
  left: 14px;
  top: 44px;
  animation-delay: -0.2796420581655481s;
}
.ldio-tiuij0da2nb > div:nth-child(7) {
  transform: rotate(180deg);
  transform-origin: 20px 50px;
}.ldio-tiuij0da2nb div:nth-child(8) > div {
  left: 18px;
  top: 29px;
  animation-delay: -0.2237136465324385s;
}
.ldio-tiuij0da2nb > div:nth-child(8) {
  transform: rotate(210deg);
  transform-origin: 24px 35px;
}.ldio-tiuij0da2nb div:nth-child(9) > div {
  left: 29px;
  top: 18px;
  animation-delay: -0.16778523489932887s;
}
.ldio-tiuij0da2nb > div:nth-child(9) {
  transform: rotate(240deg);
  transform-origin: 35px 24px;
}.ldio-tiuij0da2nb div:nth-child(10) > div {
  left: 44px;
  top: 14px;
  animation-delay: -0.11185682326621925s;
}
.ldio-tiuij0da2nb > div:nth-child(10) {
  transform: rotate(270deg);
  transform-origin: 50px 20px;
}.ldio-tiuij0da2nb div:nth-child(11) > div {
  left: 59px;
  top: 18px;
  animation-delay: -0.055928411633109625s;
}
.ldio-tiuij0da2nb > div:nth-child(11) {
  transform: rotate(300deg);
  transform-origin: 65px 24px;
}.ldio-tiuij0da2nb div:nth-child(12) > div {
  left: 70px;
  top: 29px;
  animation-delay: 0s;
}
.ldio-tiuij0da2nb > div:nth-child(12) {
  transform: rotate(330deg);
  transform-origin: 76px 35px;
}
.loadingio-spinner-spin-jpvlv996r {
  width: 35px;
  height: 35px;
  display: inline-block;
  overflow: hidden;
  background: rgba(255, 255, 255, 0.0038508064516129537);
}
.ldio-tiuij0da2nb {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.35);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-tiuij0da2nb div { box-sizing: content-box; }
/* generated by https://loading.io/ */



</style>
<body>



<div class="main-width">
  <form id="command-form" autocomplete="off">
    <label for="command">Command</label>
    <input type="text" id="command" placeholder="Command"> 
    <input type="submit" value="Submit">
  </form>


  <div class="loadingio-spinner-spin-jpvlv996r" style="display: none;"><div class="ldio-tiuij0da2nb">
  <div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div>
  </div></div>

  <ul class="command_result">

  </ul>

  <ul class="command_list" style="color: #3d5d59;font-size: 15px;">
    <li>make:module-{name}</li>
    <li>make:model-{name}-{location} default root location</li>
    <li>make:controller-{name}-{location} default root location</li>
    <li>make:controller-{name}-{location} default root location</li>
    <li>make:middleware-{name}-{location} default root location</li>
    <li>make:database-{name}-{location} default root location</li>
    <li>make:database_factory-{name}-{location} default root location</li>
    <li>database-install</li>
    <li>database-dummy-install</li>
  </ul>

</div>

<script src="//code.jquery.com/jquery-3.5.1.min.js"></script>
<script>

	var $doc = jQuery(document);

	$doc.ready(function ($) {
		$doc.on('submit', '#command-form', function (e) {
			e.preventDefault();
      $('.loadingio-spinner-spin-jpvlv996r').css('display', 'block');
      $('ul.command_result').html('');
			$.ajax({
				type: 'POST',
				url:  '<?php echo url('command_create'); ?>',
				data:{
					command: $(this).find('#command').val()
				},
				success: function(data){
          $('.loadingio-spinner-spin-jpvlv996r').css('display', 'none');
					if (data.error == 'no') {
						$('#command').val('');
            $('ul.command_result').append('<li>'+data.msg+'</li>');
            $.each(data.items, function(i, item) {
                $('ul.command_result').append('<li>'+item+'</li>');
            });
					}else{
            if (undefined !== data.msg) {

						  $('ul.command_result').append('<li>'+data.msg+'</li>');
					 
            }
          }

					// console.log(data);
				}
			});
		});






	});

</script>


</body>
</html>
